name: CI Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'docs/**'
      - '.github/**'

permissions:
  contents: read
  issues: read
  pull-requests: write
  checks: write

env:
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit

      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          dotnet-version: 10.0.x

      - name: 'Restore external dependencies'
        run: dotnet restore

      - name: 'Build'
        id: build
        run: dotnet build --configuration Debug --no-restore

      - name: 'Test'
        id: test
        run: dotnet run --configuration Release --coverage --coverage-output-format cobertura --report-github --project tests/AspNet.ApiKeyAuth.Tests/AspNet.ApiKeyAuth.Tests.csproj
